/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package e.doc.docApp;

import e.doc.service.exception.ServiceException;
import e.doc.service.sqllite.ServiceSQLLite;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class EDocs {
    private static Logger logger = LogManager.getLogger(EDocs.class);

    public static void main(String[] args) {
        //ListenerOutFolder loutf = new ListenerOutFolder();
        try {
            ServiceSQLLite serviceSQLLite = new ServiceSQLLite();
            serviceSQLLite.initDB();
            //ListenerWeb listenerWeb = new ListenerWeb();
            //ListenerInFolder linf = new ListenerInFolder();
            ListenerHolderFolder listenerHolderFolder= new ListenerHolderFolder();
        } catch (ServiceException e) {
            logger.error("Application Error - " + e.getMessage());
        }
        //ListenerInFolder linf = new ListenerInFolder();
        //ListenerOutFolder loutf = new ListenerOutFolder();
    }
}
