/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package e.doc.docApp;

public class EDocs {
    //private static Logger logger = LogManager.getLogger(EDocs.class);
    public static void main(String[] args) {
        System.setProperty("log4j2.disable.jmx", Boolean.TRUE.toString());
        //System.setProperty("log4j2.disable.jmx", Boolean.TRUE.toString());
        //logger.info("Start scaners");
        //ListenerInFolder linf = new ListenerInFolder();
        ListenerOutFolder loutf = new ListenerOutFolder();
    }
}
