/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package e.doc.docApp;

import e.doc.service.Service;
import e.doc.service.ServiceCTTImpl;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.Arrays;
import java.util.Properties;
import java.util.regex.Pattern;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

class ListenerOutFolder implements Runnable {
    private static Logger logger = LogManager.getLogger(ListenerOutFolder.class);
    final String TAG = "ListenerOutFolder";
    private Thread thread;
    Properties properties;
    Service service = new ServiceCTTImpl();

    String pathOutPost;
    String pathOutBackup;
    String pathOut;
    String regexSmToProvider;
    int provederId;

    public ListenerOutFolder() {
        thread = new Thread(this, "out");
        properties = service.getAppProperty();
        pathOutPost = properties.getProperty("path.out.post");
        pathOutBackup = properties.getProperty("path.out.backup");
        pathOut = properties.getProperty("path.out");
        regexSmToProvider = properties.getProperty("xml.regexp.out.post");
        provederId = Integer.parseInt(properties.getProperty("provider.id"));
        thread.start();
    }

    @Override
    public void run() {
        logger.info(TAG, "Out thread: ");
        //while (true) {
            /*try {
                Thread.sleep(10000);
            } catch (InterruptedException e) {
                logger.info("e" + e);
                throw new RuntimeException(e);
            }*/

        File dirin = new File(pathOutPost);
        String[] files = dirin.list();
        logger.info("files - " + Arrays.toString(files));
        for (String s : files) {
            logger.info("Check file - " + s);
            File file = new File(pathOutPost + s);
            if (Pattern.compile("^[\\d,_]+\\.(XML)$")
                    .matcher(s)
                    .matches()) {
                logger.info("Start convert SM to CTT file - " + pathOutPost + s + ".");
                String fileName = new ServiceCTTImpl().convertFormSM(file, pathOut);
                zipFile(fileName);
            } else if(Pattern.compile(".*\\.(Reply)\\.(xml)$")
                    .matcher(s)
                    .matches()) {

                logger.info("else - " + s);
            }
            file.delete();
        }
        //}
    }

    void zipFile(String fileName){
        if(fileName!=null)
        try(ZipOutputStream zout = new ZipOutputStream(new FileOutputStream(pathOut + fileName.substring(0,fileName.length()-4)+".zip"));
            FileInputStream fis= new FileInputStream(fileName);)
        {
            ZipEntry entry1=new ZipEntry(pathOut+fileName);
            zout.putNextEntry(entry1);
            // считываем содержимое файла в массив byte
            byte[] buffer = new byte[fis.available()];
            fis.read(buffer);
            // добавляем содержимое к архиву
            zout.write(buffer);
            // закрываем текущую запись для новой записи
            zout.closeEntry();
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }
}
