/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package e.docs.docApp;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class EDocs {


    private static Logger logger = LogManager.getLogger(EDocs.class);
    public static void main(String[] args) {
        //logger.info("Start scaners");
        ListenerInFolder linf = new ListenerInFolder();
        //ListenerOutFolder loutf = new ListenerOutFolder();
    }


}
